
services:
  opensearch:
    image: opensearchproject/opensearch:2.14.0
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=${OPENSEARCH_INITIAL_ADMIN_PASSWORD}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
      - "9600:9600"
    healthcheck:
      test: ["CMD", "curl", "-kf", "-u", "admin:${OPENSEARCH_INITIAL_ADMIN_PASSWORD}", "https://localhost:9200/_cluster/health"]
      interval: 10s
      timeout: 5s
      retries: 30
    networks:
      - opensearch_net

  dashboards:
    image: opensearchproject/opensearch-dashboards:2.14.0
    ports:
      - "5601:5601"
    environment:
      OPENSEARCH_HOSTS: 'https://opensearch:9200'
      OPENSEARCH_USERNAME: admin
      OPENSEARCH_PASSWORD: ${OPENSEARCH_INITIAL_ADMIN_PASSWORD}
      OPENSEARCH_SSL_VERIFICATIONMODE: none
    depends_on:
      - opensearch
    networks:
      - opensearch_net

networks:
  opensearch_net:
    driver: bridge

